/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostRouteImport } from './routes/host'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as HostRoomRoomIdRouteImport } from './routes/host.room.$roomId'
import { Route as HostQuizQuizIdRouteImport } from './routes/host.quiz.$quizId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostRoute,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoomRoomIdRoute = HostRoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => HostRoute,
} as any)
const HostQuizQuizIdRoute = HostQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => HostRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/play/$code': typeof PlayCodeRoute
  '/host/': typeof HostIndexRoute
  '/host/quiz/$quizId': typeof HostQuizQuizIdRoute
  '/host/room/$roomId': typeof HostRoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/play/$code': typeof PlayCodeRoute
  '/host': typeof HostIndexRoute
  '/host/quiz/$quizId': typeof HostQuizQuizIdRoute
  '/host/room/$roomId': typeof HostRoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/play/$code': typeof PlayCodeRoute
  '/host/': typeof HostIndexRoute
  '/host/quiz/$quizId': typeof HostQuizQuizIdRoute
  '/host/room/$roomId': typeof HostRoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/host'
    | '/login'
    | '/play/$code'
    | '/host/'
    | '/host/quiz/$quizId'
    | '/host/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/play/$code'
    | '/host'
    | '/host/quiz/$quizId'
    | '/host/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/host'
    | '/login'
    | '/play/$code'
    | '/host/'
    | '/host/quiz/$quizId'
    | '/host/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostRoute: typeof HostRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlayCodeRoute: typeof PlayCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof HostRoute
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/room/$roomId': {
      id: '/host/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/host/room/$roomId'
      preLoaderRoute: typeof HostRoomRoomIdRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/quiz/$quizId': {
      id: '/host/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/host/quiz/$quizId'
      preLoaderRoute: typeof HostQuizQuizIdRouteImport
      parentRoute: typeof HostRoute
    }
  }
}

interface HostRouteChildren {
  HostIndexRoute: typeof HostIndexRoute
  HostQuizQuizIdRoute: typeof HostQuizQuizIdRoute
  HostRoomRoomIdRoute: typeof HostRoomRoomIdRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostIndexRoute: HostIndexRoute,
  HostQuizQuizIdRoute: HostQuizQuizIdRoute,
  HostRoomRoomIdRoute: HostRoomRoomIdRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostRoute: HostRouteWithChildren,
  LoginRoute: LoginRoute,
  PlayCodeRoute: PlayCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
